export type TemplateResult<T = unknown> = { key: string; data: T; pendingConfirmation: boolean };
export type TemplateTheme = { bg: string; fg: string; card: string; muted: string; action: string; onaction: string };
export type TemplateProject = { id: string; name: string };
export type SelectedFile = { name: string; mimeType: string; size: number; base64: string };
export type SpeechRecognitionOptions = { language?: 'auto' | 'en' | 'zh' };
export type TemplateActionRecord<T> = { key: string; revision: number; updatedAt: number; data: T };
export type TemplateActionPage<T> = { records: TemplateActionRecord<T>[]; next: { beforeTime: number; beforeKey: string } | null };
export type TemplateActionTypes = Record<string, { input: object; output: unknown }>;
export declare class TemplateHostError extends Error { readonly code: string; constructor(message: string, code?: string); }
export interface HostBridge { postMessage(message: string): void; onmessage: ((event: { data: string }) => void) | null; }
export declare class MutCubeTemplateClient {
  constructor(bridge?: HostBridge);
  call<T = unknown>(capability: string, input: object, requestId?: string): Promise<T>;
  invoke<T = unknown>(actionId: string, data: object, requestId?: string): Promise<TemplateResult<T>>;
  readonly data: {
    query<T = unknown>(actionId: string, cursor?: object): Promise<TemplateResult<T>>;
    create<T = unknown>(actionId: string, value: object, requestId?: string): Promise<TemplateResult<T>>;
    update<T = unknown>(actionId: string, key: string, expectedRevision: number, value: object): Promise<TemplateResult<T>>;
    delete<T = unknown>(actionId: string, key: string, expectedRevision: number): Promise<TemplateResult<T>>;
  };
  readonly ai: { generate<T = unknown>(actionId: string, input: object, requestId?: string): Promise<TemplateResult<T>> };
  readonly project: { info(): Promise<TemplateProject> };
  readonly permissions: { status(): Promise<{ granted: string[]; available: string[]; networkDomains: string[] }> };
  readonly ui: { theme(): Promise<TemplateTheme>; notice(message: string): Promise<string>; confirm(title: string, message: string): Promise<boolean> };
  readonly navigation: { openChat(): Promise<string> };
  readonly file: { pick(): Promise<SelectedFile> };
  readonly media: { pickImage(): Promise<SelectedFile> };
  readonly clipboard: { read(): Promise<string> };
  readonly network: { fetch(url: string): Promise<{ status: number; body: string; contentType: string }> };
  readonly speech: {
    speak(text: string): Promise<{ state: 'finished' | 'stopped' }>;
    stop(): Promise<string>;
    recognize(options?: SpeechRecognitionOptions): Promise<{ text: string } | { cancelled: true }>;
    stopRecognition(): Promise<string>;
  };
  on(event: string, listener: (detail: unknown) => void): () => void;
}
export declare function connect(bridge?: HostBridge): MutCubeTemplateClient;
/** Compile-time Action typing generated by `mutcube-template types`; runtime behavior is identical to connect(). */
export interface TypedTemplateClient<Actions extends Record<keyof Actions, { input: object; output: unknown }>> extends Omit<MutCubeTemplateClient, 'invoke'> {
  invoke<K extends keyof Actions & string>(actionId: K, data: Actions[K]['input'], requestId?: string): Promise<TemplateResult<Actions[K]['output']>>;
}
export declare function connectTyped<Actions extends Record<keyof Actions, { input: object; output: unknown }>>(bridge?: HostBridge): TypedTemplateClient<Actions>;
